# Generated by Django 6.1 on 2026-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='port',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
