# Generated by Django 6.1 on 2026-08-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_commandhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_percent', models.FloatField(null=True)),
                ('disk_percent', models.CharField(max_length=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='servers.server')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
